framework:
    cache:
        pools:
            cache.redis:
                adapter: cache.adapter.redis
                provider: app.redis_provider

services:
    app.redis_provider:
        class: Predis\Client
        arguments:
            - 'redis://localhost'
            - { retry_interval: 2, timeout: 10 }
